### ISSUE TITLE
为什么纯文本过滤后会自动加上p标签?

### ISSUE THREAD

**Issue by w708833018** [phith0n/XssHtml#2]
比如 转义前 : '你好啊'
转以后: '<p>你好啊</p>'

能不能不加p标签
如何修改代码呢

**Comment by w708833018** [comment]
转义后 "p标签 你好啊 p标签"

**Comment by Ltre** [comment]
这个我也发现了，目前先用临时方案来解决

``` php
/**
 * 支持单个或批量
 * @param array $items 待处理数组，引用变量。若传入字符串，则当做单个来处理。
 * @param bool $fullfilter 默认处理数组全部元素
 * @param array $needKeys 需要处理的元素所在的键，该参数仅在$fullfilter=false时有效
 */
function xssFilter(&$items = array(), $fullfilter = true, $needKeys = array()){
    $filter = function(&$v){
        $xss = new XssHtml($v);
        $v = $xss->getHtml();
        $v = preg_replace(array('/\\n\<p\>/is', '/\<\/p\>\\n/is'), '', $v);
    };
    if (is_string($items)) {
        $filter($items);
        return;
    }
    foreach ($items as $k => &$v) {
        if ($fullfilter || in_array($k, $needKeys) && is_string($v)) {
            $filter($v);
        }
    }
}
```

调用示例：

``` php
$data = array(
    'a' => '<script>alert()</script>', 
    'b' => 2,
    'c' => 'javascript:void(0)',
);
$data1 = $data2 = $data;
$data3 = '<div onload="javascript:location.href=\'/\';"></div>';

xssFilter($data1); //批量处理：针对全部字段过滤
xssFilter($data2, false, array('a')); //批量处理：针对a字段对应的内容进行过滤
xssFilter($data3); //单个字符串处理

var_dump(compact('data1', 'data2', 'data3'));
```

以上针对版本：[3ab742d](https://github.com/phith0n/XssHtml/commit/3ab742dceee7002e75b322ff5783c2e9dc226708)

[goto☞](https://github.com/Ltre/xsshtml-demo/blob/master/README.md)

**Comment by phith0n** [comment]
我会抽时间处理（今天或明天），感谢提出来~

**Comment by phith0n** [comment]
进行了修改，你们看一下是否OK，影不影响正常业务。

**Comment by w708833018** [comment]
感谢修改
我刚替换上了
我注意到你改的这里 “<nouse>" . $this->m_xss . "</nouse>"”
这个 nouse 是什么意思

**Comment by w708833018** [comment]
<div style="position: absolute;top:500px;left: 50px;">
    <img src="http://qlogo2.store.qq.com/qzone/1548112833/1548112833/30" alt="">
</div>

**Comment by w708833018** [comment]
<H5>
你好
</H5>

**Comment by w708833018** [comment]
<h5  style='color:#ff0000'>
你好
<h5>

**Comment by w708833018** [comment]
还有一些问题：
  过滤后的内容会自动加上两个换行
比如：‘你好啊’
会过滤成: 
//换行  
   你好啊
//换行

**Comment by phith0n** [comment]
nouse相当于一个占位符，避免DOM自动给纯文本添加p。最后还是会过滤掉。
加换行的我处理了，看看会不会影响使用效果。
css白名单我暂时没有做，所以这个问题是已知问题没办法。如果实在不行可以将m_AllowAttr中的style去掉，不允许style属性出现。
编辑器里，部分编辑器是不使用style控制样式的，你可以根据自己的富文本编辑器的情况调整m_AllowAttr和m_AllowTag。

**Comment by w708833018** [comment]
好的 谢谢
