### ISSUE TITLE
求帮忙

### ISSUE THREAD

**Issue by JaxsonWang** [phith0n/XssHtml#4]
感谢作者写个好用的过滤器。

我是php小白，不是太熟悉。

现在有个问题，就是我在文章有个标签`<!--more-->`，发现被过滤了，如何让它加入白名单？

@phith0n 谢谢谢谢！

**Comment by JaxsonWang** [comment]
```php
require('xsshtml.class.php');
$html = '<!--more-->';
$xss = new XssHtml($html);
$html = $xss->getHtml();
echo $html;
```

**Comment by phith0n** [comment]
原理上讲这个源码不太好处理你这个需求。

**Comment by JaxsonWang** [comment]
呃，有个思路，就是在过滤前吧换成{--more--}，过滤后再换过来，就这样...

**Comment by phith0n** [comment]
曲线救国

**Comment by stevinus73** [comment]
require('xsshtml.class.php');
$html = '{--more--}';
$xss = new XssHtml($html);
$html = $xss->getHtml();
echo $html;
